In [1]:
import pandas as pd

import numpy as np

In [2]:
# Read the data and set it into a variable

menu_df = pd.read_csv('menu_data.csv')

sales_df = pd.read_csv('sales_data.csv', index_col = "Line_Item_ID", parse_dates = True, infer_datetime_format = True)

sales_df.head(10)

                    Date  Credit_Card_Number  Quantity              Menu_Item
Line_Item_ID
1             01-01-2017    7437926611570799         1       spicy miso ramen
2             01-01-2017    7437926611570799         1       spicy miso ramen
3             01-01-2017    8421920068932819         3      tori paitan ramen
4             01-01-2017    8421920068932819         3      tori paitan ramen
5             01-01-2017    4787310681569648         1   truffle butter ramen
6             01-01-2017    4787310681569648         1   truffle butter ramen
7             01-01-2017    8252818705821725         1         tonkotsu ramen
8             01-01-2017    8252818705821725         1         tonkotsu ramen
9             01-01-2017    3119034881407323         1  vegetarian spicy miso
10            01-01-2017    3119034881407323         1  vegetarian spicy miso

In [3]:
sales_df.duplicated().sum()

37062

In [4]:
sales_df.isnull().sum()

Date                  0
Credit_Card_Number    0
Quantity              0
Menu_Item             0
dtype: int64

In [5]:
sales_df.drop_duplicates(inplace=True)

In [6]:
sales_df.duplicated().sum()

0

In [7]:
sales_df.head(10)

                    Date  Credit_Card_Number  Quantity              Menu_Item
Line_Item_ID
1             01-01-2017    7437926611570799         1       spicy miso ramen
3             01-01-2017    8421920068932819         3      tori paitan ramen
5             01-01-2017    4787310681569648         1   truffle butter ramen
7             01-01-2017    8252818705821725         1         tonkotsu ramen
9             01-01-2017    3119034881407323         1  vegetarian spicy miso
11            01-01-2017    5185620052605569         1             shio ramen
13            01-01-2017    1625774198697856         1      tori paitan ramen
15            01-01-2017     505248472056578         1  vegetarian spicy miso
17            01-01-2017    5010864392617689         1       spicy miso ramen
19            01-01-2017    1792739336416381         2   truffle butter ramen

In [8]:
sales_df['Menu_Item'].value_counts()

vegetarian spicy miso                             3411
tori paitan ramen                                 3409
spicy miso ramen                                  3401
tonkotsu ramen                                    3400
burnt garlic tonkotsu ramen                       3385
shio ramen                                        3372
soft-shell miso crab ramen                        3371
truffle butter ramen                              3363
vegetarian curry + king trumpet mushroom ramen    3343
nagomi shoyu                                      3330
miso crab ramen                                   3277
Name: Menu_Item, dtype: int64

In [9]:
sales_sliced_df = sales_df.groupby(['Menu_Item']).count()

In [10]:
menu_sliced_df = menu_df.loc[14:24, :]

In [11]:
sales_sliced_df.drop(columns = ['Date', 'Credit_Card_Number'], inplace=True)

In [12]:
sales_sliced_df.sort_values("Menu_Item", ascending = True, inplace = True)

sales_sliced_df

                                                Quantity
Menu_Item
burnt garlic tonkotsu ramen                         3385
miso crab ramen                                     3277
nagomi shoyu                                        3330
shio ramen                                          3372
soft-shell miso crab ramen                          3371
spicy miso ramen                                    3401
tonkotsu ramen                                      3400
tori paitan ramen                                   3409
truffle butter ramen                                3363
vegetarian curry + king trumpet mushroom ramen      3343
vegetarian spicy miso                               3411

In [13]:
menu_sliced_df.sort_values("item", ascending = True, inplace = True)

menu_sliced_df

<ipython-input-13-c5052d508c4b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  menu_sliced_df.sort_values("item", ascending = True, inplace = True)

,item,category,description,price,cost
22,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6
18,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6
14,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5
15,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5
19,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7
16,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5
21,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6
20,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6
24,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7
23,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7
17,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5

In [14]:
menu_sliced_df.reset_index(inplace=True)

In [15]:
menu_sliced_df.drop(columns = 'index', inplace = True)

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [16]:
menu_sliced_df

,item,category,description,price,cost
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5

In [17]:
sales_sliced_df.reset_index(inplace=True)

In [18]:
sales_sliced_df

                                         Menu_Item  Quantity
0                      burnt garlic tonkotsu ramen      3385
1                                  miso crab ramen      3277
2                                     nagomi shoyu      3330
3                                       shio ramen      3372
4                       soft-shell miso crab ramen      3371
5                                 spicy miso ramen      3401
6                                   tonkotsu ramen      3400
7                                tori paitan ramen      3409
8                             truffle butter ramen      3363
9   vegetarian curry + king trumpet mushroom ramen      3343
10                           vegetarian spicy miso      3411

In [19]:
total_sales_df = pd.concat([menu_sliced_df, sales_sliced_df], axis = 'columns', join = 'inner')

total_sales_df

,item,category,description,price,cost,Menu_Item,Quantity
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6,burnt garlic tonkotsu ramen,3385
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6,miso crab ramen,3277
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5,nagomi shoyu,3330
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5,shio ramen,3372
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7,soft-shell miso crab ramen,3371
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5,spicy miso ramen,3401
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6,tonkotsu ramen,3400
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6,tori paitan ramen,3409
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7,truffle butter ramen,3363
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7,vegetarian curry + king trumpet mushroom ramen,3343
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5,vegetarian spicy miso,3411

In [20]:
total_sales_df.drop(columns = 'Menu_Item', inplace = True)

total_sales_df

,item,category,description,price,cost,Quantity
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6,3385
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6,3277
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5,3330
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5,3372
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7,3371
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5,3401
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6,3400
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6,3409
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7,3363
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7,3343
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5,3411

In [21]:
total_sales_df.columns = ['Menu_Item', 'Category', 'Description', 'Price', 'Cost','Count']

total_sales_df

,Menu_Item,Category,Description,Price,Cost,Count
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6,3385
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6,3277
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5,3330
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5,3372
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7,3371
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5,3401
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6,3400
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6,3409
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7,3363
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7,3343
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5,3411

In [22]:
total_sales_df['Revenue'] = total_sales_df['Price']*total_sales_df['Count']

total_sales_df

,Menu_Item,Category,Description,Price,Cost,Count,Revenue
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6,3385,47390.0
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6,3277,39324.0
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5,3330,36630.0
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5,3372,37092.0
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7,3371,47194.0
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5,3401,40812.0
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6,3400,44200.0
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6,3409,44317.0
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7,3363,47082.0
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7,3343,43459.0
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5,3411,40932.0

In [23]:
total_sales_df['COGS'] = total_sales_df['Cost'] * total_sales_df['Count']

In [24]:
total_sales_df

,Menu_Item,Category,Description,Price,Cost,Count,Revenue,COGS
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6,3385,47390.0,20310
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6,3277,39324.0,19662
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5,3330,36630.0,16650
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5,3372,37092.0,16860
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7,3371,47194.0,23597
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5,3401,40812.0,17005
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6,3400,44200.0,20400
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6,3409,44317.0,20454
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7,3363,47082.0,23541
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7,3343,43459.0,23401
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5,3411,40932.0,17055

In [25]:
total_sales_df['Profit'] = total_sales_df['Revenue'] - total_sales_df['COGS']

total_sales_df

,Menu_Item,Category,Description,Price,Cost,Count,Revenue,COGS,Profit
0,burnt garlic tonkotsu ramen,entree,"rich, shoyi and burnt garlic seasoned niman ra...",14.0,6,3385,47390.0,20310,27080.0
1,miso crab ramen,entree,house miso crab blend + vegan dashi; slow brai...,12.0,6,3277,39324.0,19662,19662.0
2,nagomi shoyu,entree,shoyu seasoned clear double stock (organic chi...,11.0,5,3330,36630.0,16650,19980.0
3,shio ramen,entree,sea salt seasoned clear double stock (organic ...,11.0,5,3372,37092.0,16860,20232.0
4,soft-shell miso crab ramen,entree,house miso crab blend + vegan dashi; fried who...,14.0,7,3371,47194.0,23597,23597.0
5,spicy miso ramen,entree,house togarashi miso blend + niman ranch pork ...,12.0,5,3401,40812.0,17005,23807.0
6,tonkotsu ramen,entree,"rich, shoyi seasoned niman ranch pork bone sto...",13.0,6,3400,44200.0,20400,23800.0
7,tori paitan ramen,entree,"rich, shoyu seasoned double stock (organic chi...",13.0,6,3409,44317.0,20454,23863.0
8,truffle butter ramen,entree,"rich, shoyu seasoned niman ranch prok bone sto...",14.0,7,3363,47082.0,23541,23541.0
9,vegetarian curry + king trumpet mushroom ramen,entree,house curry blend + vegan dashi; fried king tr...,13.0,7,3343,43459.0,23401,20058.0
10,vegetarian spicy miso,entree,house togarashi miso blend + vegan dashi; temp...,12.0,5,3411,40932.0,17055,23877.0

In [27]:
total_sales_df.to_csv('total_sales_data.csv')